export const content = [
  {
    id: 1,
    title: 'Módulo 1: Alinhando expectativas - O que vamos aprender?',  
    week: ["Semana 1"],  
    episodes: [
      { id: 1, title: 'Sobre o curso' },
      { id: 2, title: 'Sobre o(s) instrutor(es)' },      
      { id: 3, title: 'O mercado de trabalho para Devs'},
      { id: 4, title: 'No-code, Low-code ou Hard-code?'},
      { id: 5, title: 'De onde partir e pra onde ir? (Roadmaps)'},
      { id: 6, title: 'Mitos e verdades'},
    ],
  },
  {
    id: 2,
    title: 'Módulo 2: Primeiro contato - O Alicerce: Algoritmos e Lógica',
    week:["Semanas 2, 3, 4, 5, 6, 7 e 8"],
    episodes: [
      { id: 1, title: 'O que são algoritmos e onde podem ser encontrados?' },
      { id: 2, title: 'Fundamentos são o maior diferencial!' },
      { id: 3, title: 'Matemática computacional - Bit, Byte e Palavra' },
      { id: 4, title: 'Processamento de dados - Dado e Informação' },
      { id: 5, title: 'Pensando e conversando com a máquina' },
      { id: 6, title: 'Tipos de dados' },
      { id: 7, title: 'Interação entre os tipos de dados' },
      { id: 8, title: 'Exercícios sobre tipos de dados' },
      { id: 9, title: 'A matemágica do resto na computação' },
      { id: 10, title: 'Expressões lógicas - A tabela verdade' },
      { id: 11, title: 'Expressões lógicas - Operadores lógicos e relacionais' },
      { id: 12, title: 'A lei de Morgan' },
      { id: 13, title: 'Estático vs Dinâmico' },
      { id: 14, title: 'Entrada e saída de dados' },
      { id: 15, title: 'Operadores aritméticos' },
      { id: 16, title: 'Manipulando datas - O problema' },
      { id: 17, title: 'Manipulando datas - Exemplos de solução manual' },
      { id: 18, title: 'Exercícios sobre Manipulando datas' },
      { id: 19, title: 'Exercícios sobre Manipulando datas' },
      { id: 20, title: 'Operadores condicionais - If' },
      { id: 21, title: 'Operadores condicionais - Else' },
      { id: 22, title: 'Operadores condicionais - Else If' },
      { id: 23, title: 'Exercícios sobre Operadores condicionais' },
      { id: 24, title: 'Loops - While' },
      { id: 25, title: 'Loops - For' },
      { id: 26, title: 'Loops - Foreach' },
      { id: 27, title: 'Loops - Map' },
      { id: 28, title: 'Loops - DoWhile' },
      { id: 29, title: 'Loops - DoWhile' },
      { id: 30, title: 'Exercícios sobre Loops' },      
      { id: 31, title: 'Desafio de raciocínio lógico' },
      { id: 32, title: 'Reaprendendo a pensar a matemática - Multiplicação' },
      { id: 33, title: 'Reaprendendo a pensar a matemática - Divisão e conquista' },
      { id: 34, title: 'Reaprendendo a pensar a matemática - Resto da divisão' },
      { id: 35, title: 'Reaprendendo a pensar a matemática - Porcentagem' },
      { id: 36, title: 'Reaprendendo a pensar a matemática - Parte inteira e fracionária' },
      { id: 37, title: 'Reaprendendo a pensar a matemática - Teorema de Pitágoras' },
      { id: 38, title: 'Exercícios de lógica matemática' },
      { id: 39, title: 'Vetores - O que são e para que servem?' },
      { id: 40, title: 'Vetores - Principais funções' },
      { id: 41, title: 'Vetores - Vetores associados' },
      { id: 42, title: 'Exercícios sobre Vetores' },
      { id: 43, title: 'Açúcares sintáticos' },
      { id: 44, title: 'Strings - O que são e para que servem?' },
      { id: 45, title: 'Manipulação de strings - Comparação de Strings' },
      { id: 46, title: 'Manipulação de strings - Principais funções' },
      { id: 47, title: 'Manipulação de strings - Principais funções' },
      { id: 48, title: 'Exercício sobre Strings' },
    ],
  },
  {
    id: 3,
    title: 'Módulo 3: Mundo real e computacional - Um toque de mundo real ao código: POO',
    week:['Semanas 9, 10, 11, 12, 13 e 14'],
    episodes: [
      { id: 1, title: 'O que é POO e para que serve?' },
      { id: 2, title: 'Classes e Objetos' },
      { id: 3, title: 'Métodos/Funções' },
      { id: 4, title: 'Pensando OO - Simple single objects' },
      { id: 5, title: 'Construtores' },
      { id: 6, title: 'Getters e Setters' },
      { id: 7, title: 'Herança' },
      { id: 8, title: 'Encapsulamento' },
      { id: 9, title: 'Polimorfismo' },
      { id: 10, title: 'Projeto prático' },
      { id: 9, title: 'REST API' },
      { id: 9, title: 'REST' },
    ],
  },
  {
    id: 4,
    title: 'Módulo 4: Persistindo dados - Persistindo Dados e extraindo informações relevantes: Banco de dados',
    week:['Semanas 15, 16, 17 e 18'],
    episodes: [
      { id: 1, title: 'O que é banco de dados?' },
      { id: 2, title: 'SQL, NOSQL e outros' },
      { id: 3, title: 'Modelagem de Dados e Esquemas de Banco de Dados' },
      { id: 4, title: 'SQL Básico: Criação de Dados' },
      { id: 5, title: 'SQL Básico: Consulta de Dados' },
      { id: 6, title: 'SQL Básico: Manipulação de Dados' },
      { id: 7, title: 'Exercício de manipulação de dados' },
      { id: 8, title: 'SQL Intermediário: Joins' },
      { id: 9, title: 'SQL Intermediário: Sub-consultas' },
      { id: 10, title: 'Exercício de Joins e sub-consultas' },
      { id: 11, title: 'SQL Avançado: Funções' },
      { id: 12, title: 'SQL Avançado: Transações' },
      { id: 13, title: 'SQL Avançado: Gatilhos' },
      { id: 14, title: 'Exercício de Funções, Transações e gatilhos' },
      { id: 15, title: 'Tendências em Banco de Dados: Big Data e Data Science'},
      { id: 16,title: 'Projeto Final: Desenvolvendo um Banco de Dados Real a partir de ER'}
    ],
  },
  {
    id: 5,
    title: 'Módulo 5: Primeiro projeto real completo - API Persistida: ',
    week:[],
    episodes: [
      { id: 1, title: 'O que são metadados' },
      { id: 2, title: 'Fonts' },
      { id: 3, title: 'Layout responsivo com TailwindCSS' },
      { id: 4, title: 'Layout default' },
      { id: 5, title: 'Criando componente Topbar' },
      { id: 6, title: 'Criando componente Sidebar' },
      { id: 7, title: 'Criando componente Sidebar para Mobile' },
      { id: 8, title: 'O que são middlewares?' },
      { id: 9, title: 'Redirecionamento de páginas' },
    ],
  },
  {
    id: 6,
    title: 'Módulo 6: Configurando Banco de Dados',
    week:[],
    episodes: [
      { id: 1, title: 'Configurando o PlanetScale' },
      { id: 2, title: 'Configurando Prisma ORM' },
    ],
  },
  {
    id: 7,
    title: 'Módulo 7: Criando Curso',
    week:[],
    episodes: [
      { id: 1, title: 'Criando página de Novo Curso' },
      { id: 2, title: 'O que são Server Actions?' },
      { id: 3, title: 'Novo curso' },
      { id: 4, title: 'Criando tabela de Cursos' },
      { id: 5, title: 'Entendendo Data Fetching' },
      { id: 6, title: 'Criando API de Cursos' },
      { id: 7, title: 'Edição de Cursos' },
      { id: 8, title: 'Edição de Episódios' },
      { id: 9, title: 'Publicação de Cursos' },
      { id: 10, title: 'Publicação de Episódios' },
    ],
  },
  {
    id: 8,
    title: 'Módulo 8: Listagem de Cursos',
    week: [],
    episodes: [
      { id: 1, title: 'Entendendo sobre Caching' },
      { id: 2, title: 'Lazy Loading' },
      { id: 3, title: 'Criando componente de Listagem de Curso' },
      { id: 4, title: 'Filtro para Listagem de Curso' },
    ],
  },
  {
    id: 9,
    title: 'Módulo 9: Integração com Stripe',
    week: [],
    episodes: [
      { id: 1, title: 'Configurando Stripe' },
      { id: 2, title: 'Componente de Compra de Curso' },
      { id: 3, title: 'Integração com Stripe' },
    ],
  },
  {
    id: 10,
    title: 'Módulo 10: Dashboard do Aluno',
    week: [],
    episodes: [
      { id: 1, title: 'Progresso do Aluno' },
      { id: 2, title: 'Dashboard do Aluno' },
    ],
  },
  {
    id: 11,
    title: 'Módulo 11: Deployment',
    week: [],
    episodes: [
      { id: 1, title: 'Tudo sobre a Vercel' },
      { id: 2, title: 'Configurando novo projeto na Vercel' },
      { id: 3, title: 'WebHooks Clerk' },
      { id: 4, title: 'WebHooks Stripe' },
      { id: 5, title: 'Analytics' },
    ],
  },
  {
    id: 12,
    title: 'Complementar - E-commerce do zero com Woocommerce (Low-Code)',
    week: ['Módulo Opcional'],
    episodes: [
      { id: 1, title: 'Aula extra' },
      {
        id: 2,
        title:
          'Live: Quarta-feira, 6 de dezembro · 7:00 até 8:00pm Fuso horário: America/Sao_Paulo Como participar do Google Meet Link da videochamada: https://meet.google.com/som-akuz-nbo',
      },
    ],
  },
  {
    id: 13,
    title: 'Bônus 2',
    week: [],
    episodes: [
      { id: 1, title: 'Aula extra' },
      {
        id: 2,
        title:
          'Live: Quarta-feira, 10 de janeiro de 2024 · 7:00 até 8:00pm Fuso horário: America/Sao_Paulo Como participar do Google Meet Link da videochamada: https://meet.google.com/emy-cgvp-zav',
      },
    ],
  },
];